import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog } from '@angular/material/dialog';
import { RouterModule } from '@angular/router';
import { BaseChartDirective } from 'ng2-charts';
import { ChartConfiguration, ChartData, ChartType } from 'chart.js';
import { LoteriasService } from '../../../services/loterias.service';
import { BetSummaryResponse, LotofacilBet, BetGraphicsResponse } from '../../../interfaces/lotofacil';
import { BetModalComponent } from '../bet-modal/bet-modal.component';
import { forkJoin } from 'rxjs';

@Component({
  selector: 'app-bet-report',
  standalone: true,
  imports: [CommonModule, MatCardModule, MatTableModule, MatPaginatorModule, MatIconModule, MatButtonModule, RouterModule, BaseChartDirective],
  templateUrl: './bet-report.component.html',
  styleUrls: ['./bet-report.component.scss']
})
export class BetReportComponent implements OnInit {

  summary: BetSummaryResponse = { totalBets: 0, totalInvested: 0, totalReturn: 0, balance: 0, averageHits: 0, totalAutoGenerated: 0, totalManual: 0, totalWinningBets: 0, winRate: 0};
  graphicsData!: BetGraphicsResponse;
  
  bets: LotofacilBet[] = [];
  // Adicionada a coluna autoGenerated
  displayedColumns: string[] = ['id', 'targetDrawId', 'autoGenerated', 'betDate', 'hits', 'prize', 'actions'];
  
  totalElements = 0;
  pageSize = 10;
  currentPage = 0;

  // ==== CONFIGURAÇÕES DOS GRÁFICOS ====
  public pieChartType: ChartType = 'pie';
  public pieChartOptions: ChartConfiguration['options'] = {
    responsive: true,
    plugins: { legend: { position: 'bottom' } }
  };

  public paritiesChartData: ChartData<'pie', number[], string | string[]> = { labels: [], datasets: [{ data: [] }] };
  public repetitionsChartData: ChartData<'pie', number[], string | string[]> = { labels: [], datasets: [{ data: [] }] };

  constructor(private service: LoteriasService, private dialog: MatDialog) {}

  ngOnInit(): void {
    this.loadDashboardData();
    this.loadBets();
  }

  // Busca o resumo e os gráficos em paralelo
  loadDashboardData(): void {
    forkJoin({
      summary: this.service.getBetSummary(),
      graphics: this.service.getGraphicsData()
    }).subscribe(({ summary, graphics }) => {
      this.summary = summary;
      this.graphicsData = graphics;
      this.buildCharts();
    });
  }

  loadBets(): void {
    this.service.getBetsPaginated(this.currentPage, this.pageSize).subscribe(page => {
      this.bets = page.content;
      this.totalElements = page.totalElements;
    });
  }

  buildCharts(): void {
    if (!this.graphicsData) return;

    // Gráfico de Paridade
    const pLabels = this.graphicsData.paritiesPieData.map(p => `${p.oddCount}Í / ${p.evenCount}P`);
    const pData = this.graphicsData.paritiesPieData.map(p => p.total);
    this.paritiesChartData = {
      labels: pLabels,
      datasets: [{ data: pData, backgroundColor: ['#667eea', '#764ba2', '#ff9a9e', '#fecfef', '#a18cd1'] }]
    };

    // Gráfico de Repetições
    const rLabels = this.graphicsData.repetitionsPieData.map(r => `${r.repeatedCount} Repetidas`);
    const rData = this.graphicsData.repetitionsPieData.map(r => r.total);
    this.repetitionsChartData = {
      labels: rLabels,
      datasets: [{ data: rData, backgroundColor: ['#20c997', '#28a745', '#ffc107', '#fd7e14', '#dc3545'] }]
    };
  }

  onPageChange(event: PageEvent): void {
    this.currentPage = event.pageIndex;
    this.pageSize = event.pageSize;
    this.loadBets();
  }

  openBetDetail(bet: LotofacilBet): void {
    this.dialog.open(BetModalComponent, { width: '500px', data: bet, panelClass: 'no-padding-dialog' });
  }
}