import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatTableModule } from '@angular/material/table';
import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatDialog } from '@angular/material/dialog';
import { RouterModule } from '@angular/router';
import { LoteriasService } from '../../../services/loterias.service';
import { BetSummaryResponse, LotofacilBet } from '../../../interfaces/lotofacil';
import { BetModalComponent } from '../bet-modal/bet-modal.component';

@Component({
  selector: 'app-bet-report',
  standalone: true,
  imports: [CommonModule, MatCardModule, MatTableModule, MatPaginatorModule, MatIconModule, MatButtonModule, RouterModule],
  templateUrl: './bet-report.component.html',
  styleUrls: ['./bet-report.component.scss']
})
export class BetReportComponent implements OnInit {

  summary: BetSummaryResponse = { totalBets: 0, totalInvested: 0, totalReturn: 0, balance: 0 };
  
  bets: LotofacilBet[] = [];
  displayedColumns: string[] = ['id', 'targetDrawId', 'betDate', 'hits', 'prize', 'actions'];
  
  // Controle de Paginação
  totalElements = 0;
  pageSize = 10;
  currentPage = 0;

  // Estatísticas do Painel Lateral (Página Atual)
  autoGeneratedCount = 0;
  manualCount = 0;
  winningBetsCount = 0;

  constructor(private service: LoteriasService, private dialog: MatDialog) {}

  ngOnInit(): void {
    this.loadSummary();
    this.loadBets();
  }

  loadSummary(): void {
    this.service.getBetSummary().subscribe(data => this.summary = data);
  }

  loadBets(): void {
    this.service.getBetsPaginated(this.currentPage, this.pageSize).subscribe(page => {
      this.bets = page.content;
      this.totalElements = page.totalElements;
      this.calculatePageStats(this.bets); // Calcula os gráficos sempre que virar a página
    });
  }

  calculatePageStats(bets: LotofacilBet[]): void {
    this.autoGeneratedCount = bets.filter(b => b.autoGenerated).length;
    this.manualCount = bets.length - this.autoGeneratedCount;
    this.winningBetsCount = bets.filter(b => (b.prize || 0) > 0).length;
  }

  onPageChange(event: PageEvent): void {
    this.currentPage = event.pageIndex;
    this.pageSize = event.pageSize;
    this.loadBets();
  }

  openBetDetail(bet: LotofacilBet): void {
    this.dialog.open(BetModalComponent, {
      width: '500px',
      data: bet,
      panelClass: 'no-padding-dialog'
    });
  }
}