/* Interfaces para a tabelas de totais (paridade, repetições e números) */
export interface ParityData {
  id: number;
  parity: string;
  quantity: number;
  percentage: number;
}

export interface RepetitionData {
  id: number;
  repeated: number;
  quantity: number;
  percentage: number;
}

export interface NumberData {
  id: number;
  quantity: number;
  percentage: number;
}

/* Interface para detalhes dos números sorteados do concurso */
export interface DetailsNumberDraw {
  id: number;
  number: number;
  isRepeated: boolean;
}

/* Interface para a busca de concursos salvos, o que como vem do backend */
export interface DetailedDraw {
  id: number;
  evenCount: number;
  oddCount: number;
  repeatedCount: number;
  drawDate: Date;
  drawNumbers: DetailsNumberDraw[];
  isOfficial: boolean;
}

/* Interface para detalhes dos números apostados */
export interface LotofacilBetNumber {
  id: number;
  number: number;
  isRepeated: boolean;
  wasCorrectly: boolean;
}

/* Interface para a busca de apostas salvas, o que como vem do backend */
export interface LotofacilBet {
  id: number;
  targetDrawId: number;
  evenCount: number;
  oddCount: number;
  repeatedCount: number;
  cost: number;
  hits: number;
  prize: number | null;
  betDate: string;
  checked: boolean;
  betNumbers: LotofacilBetNumber[];
  realDraw?: any; /* Pode tipar com DetailedDraw depois */
  autoGenerated: boolean;
}

/* Interface para abertura do modal de concurso */
export interface ModalData {
  draw: DetailedDraw;
  isGenerated: boolean;
  requestParams?: GenerateDrawRequest;
}

/* Paginação */
export interface Page<T> {
  content: T[];
  totalElements: number;
  totalPages: number;
  size: number;
  number: number;
}

/* Interface de View Model (o que será mostrado em tela)*/
export interface infoDrawVM {
  idDraw: number;
  oddCount: number;
  evenCount: number;
  repeatedCount: number;
  drawDate?: Date | string;
}

/* Interface auxiliar para passar contexto para a atualização de status */
export interface StatusContext {
  syncResponse?: SynchronizeResponse | null;
  manualAddId?: number | null;
}

/* Intefaces para informações dos gráficos*/
export interface ParityGroup {
  oddCount: number;
  evenCount: number;
  total: number;
}

export interface RepetitionGroup {
  repeatedCount: number;
  total: number;
}

/**************************************/
/* Interfaces de Requisições: Request */
/**************************************/
export interface GenerateDrawRequest {
  lastDrawId: string;
  evenCount: string | null;
  oddCount: string | null;
  repeatedCount: string | null;
}

export interface AddDrawRequest {
  drawId: number;
  dozens: string[]; /* Ex: ["01", "06", "07", ...] */
  drawDate: string;
}

export interface SaveBetRequest {
  betDate: string; /* Formato YYYY-MM-DD */
  targetDrawId: number;
  oddCount: number;
  evenCount: number;
  repeatedCount: number;
  betNumbers: number[]; /* Apenas um array de inteiros */
  autoGenerated: boolean
}

/***************************************/
/* Interfaces de Requisições: Response */
/*************************************(*/
export interface SynchronizeResponse {
  lastSavedDrawId: number;
  synchronizedDrawsCount: number;
  dateNextDraw: Date;
  syncMessage: string;
  nextDrawId: number;
}

export interface BetSummaryResponse {
  totalBets: number;
  totalInvested: number;
  totalReturn: number;
  balance: number;
  averageHits: number;
  totalAutoGenerated: number;
  totalManual: number;
  totalWinningBets: number;
  winRate: number;
}

export interface BetGraphicsResponse {
  paritiesPieData: ParityGroup[];
  repetitionsPieData: RepetitionGroup[];
  exactParityHits: number;
  exactRepetitionHits: number;
}

