import { Component, Inject, OnInit } from '@angular/core';
import { MAT_DIALOG_DATA, MatDialog, MatDialogModule, MatDialogRef } from '@angular/material/dialog';
import { CommonModule } from '@angular/common'; 
import { MatButtonModule } from '@angular/material/button';
import { DetailsNumberDraw, ModalData, DetailedDraw, SaveBetRequest } from '../../../interfaces/lotofacil';
import { MatIconModule } from '@angular/material/icon';
import { LotteriesService } from '../../../services/lotteries.service';
import { ConfirmDialogComponent } from '../../../shared/confirm-dialog/confirm-dialog.component';
import { infoDrawVM } from '../../../interfaces/lotofacil';
import { DebugService } from '../../../core/services/debug.service';

@Component({
  selector: 'app-draw-modal',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule, MatIconModule],
  templateUrl: './draw-modal.component.html',
  styleUrls: ['./draw-modal.component.scss']
})
export class DrawModalComponent implements OnInit {

  /* Concurso que será mostraod em tela*/
  public infoDraw!: infoDrawVM;
  public orderedResult!: DetailsNumberDraw[];
  public isGenerate: boolean = false;
  public isLoading: boolean = false;

  constructor(
    @Inject(MAT_DIALOG_DATA) public data: ModalData,
    private LotteriesService: LotteriesService,
    private dialog: MatDialog,
    private dialogRef: MatDialogRef<DrawModalComponent>,
    private debugService: DebugService,
  ) { }

  ngOnInit(): void {
    this.isGenerate = this.data.isGenerated;
    this.updateScreenData(this.data.draw);
  }

  /* Extraímos a lógica para reaproveitar ao gerar um novo */
  private updateScreenData(draw: DetailedDraw): void {
    this.infoDraw = {
      idDraw: draw.id,
      oddCount: draw.oddCount,
      evenCount: draw.evenCount,
      repeatedCount: draw.repeatedCount,
      drawDate: draw.drawDate
    };
    this.orderedResult = draw.drawNumbers.sort((a, b) => a.number - b.number);
  }

  /* Função para recriar o concurso diretamente do modal */
  public recreateDraw(): void {
    if (!this.data.requestParams || this.isLoading) return;

    this.isLoading = true;
    
    this.LotteriesService.generateDraw(this.data.requestParams).subscribe({
      next: (newDraw) => {
        /* Atualiza a tela instantaneamente sem fechar o modal */
        this.updateScreenData(newDraw);
        this.isLoading = false;
      },
      error: (err) => {
        console.error('Erro ao recriar palpite:', err);
        this.isLoading = false;
      }
    });
  }

  public betADraw(): void {
    const dialogRefConfirm = this.dialog.open(ConfirmDialogComponent, {
      width: '400px',
      data: {
        title: 'Confirmar Aposta',
        message: `Deseja registrar que você apostou os números gerados para o concurso ${this.infoDraw.idDraw}?`,
        confirmText: 'Sim, apostei',
        cancelText: 'Cancelar',
        confirmButtonColor: 'accent' /* Mesma cor do botão para manter consistência */
      }
    });

    dialogRefConfirm.afterClosed().subscribe(confirmed => {
      if (confirmed) {
        this.registerBet();
      }
    });
  }

  /* Monta o JSON e dispara para o Service */
  private registerBet(): void {
    this.isLoading = true;

    /* Pega a data de hoje no formato YYYY-MM-DD */
    const todayDate = new Date().toISOString().split('T')[0];

    const payload: SaveBetRequest = {
      betDate: todayDate,
      targetDrawId: this.infoDraw.idDraw,
      oddCount: this.infoDraw.oddCount,
      evenCount: this.infoDraw.evenCount,
      repeatedCount: this.infoDraw.repeatedCount,
      betNumbers: this.orderedResult.map(dezena => dezena.number), /* Extrai apenas os inteiros */
      autoGenerated: true
    };

    /* Imprime o JSON no console para você validar a simulação */
    this.debugService.log('JSON disparado para o Backend:', JSON.stringify(payload, null, 2));

    this.LotteriesService.saveGeneratedBet(payload).subscribe({
      next: (response) => {
        this.isLoading = false;
        
        this.dialogRef.close({ action: 'BET_SAVED' }); /* Fecha o modal do concurso */
      },
      error: (error) => {
        console.error('Erro ao registrar aposta:', error);
        this.isLoading = false;
        alert('Não foi possível registrar a aposta. Verifique o console.');
      }
    });
  }
}